name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker Image
      run: docker pull skmahajan4998/cicd-app:latest
    - name: Delete Old Docker Container
      run: docker rm -f cicd-app-container || true
    - name: Run Docker Container
      run: docker run -d -p 8080:8080 --name cicd-app-container skmahajan4998/cicd-app
