name: CI Pipeline

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      working-directory: cicd/
    - name: Build the Docker image
      run: docker build -t cicd .
      working-directory: cicd/
    - name: Push to Dockerhub
      run: docker push skmahajan4998/cicd:latest
      working-directory: cicd/
