name: CI Pipeline

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Build Project
      run: mvn clean install -DskipTests
      working-directory: cicd/
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      working-directory: cicd/
    - name: Build the Docker image
      run: docker build -t cicd-app .
      working-directory: cicd/
    - name: Push to Dockerhub
      run: docker push skmahajan4998/cicd-app:latest
      working-directory: cicd/
